# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8b23075bf466f0b735f527f5278013948af3edeff346f68b022c86df362a78d518cae1d5c55a0482615efc81f74aa16e72398f71b53f30063d49dc54b5d9357

test:
  secret_key_base: 5de291e03795262608ff67f6dc52068586e3ef4fdcf1c73ee8ead7a8fef8e2064e202eb9432afa2b116a16aed972fd34012f5306a77d0ad60a716d45d56accef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
